apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-web-ui
  labels:
    app: indefinite-studies-web-ui
spec:
  type: NodePort
  ports:
    - port: {{ .Values.global.ports.webui }}
  selector:
    app: indefinite-studies-web-ui