apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-web-ui
  labels:
    app: indefinite-studies-web-ui
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.global.ports.external.webui }}
      port: {{ .Values.global.ports.inner.webui }}
  selector:
    app: indefinite-studies-web-ui