apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.global.ports.external.nginx }} 
      port: {{ .Values.global.ports.inner.nginx }}
  selector:
    app: nginx 