apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-posts-service-postgres
  labels:
    app: indefinite-studies-posts-service-postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: indefinite-studies-posts-service-postgres