apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-auth-service-postgres
  labels:
    app: indefinite-studies-auth-service-postgres
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.global.ports.external.postgres.auth }} 
      port: {{ .Values.global.ports.inner.postgres }}
  selector:
    app: indefinite-studies-auth-service-postgres