apiVersion: v1
kind: PersistentVolume
metadata:
  name: indefinite-studies-profiles-service-postgres-pv-volume
  labels:
    type: local
    app: indefinite-studies-profiles-service-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/volume/profiles_db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: indefinite-studies-profiles-service-postgres-pv-claim
  labels:
    app: indefinite-studies-profiles-service-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi