apiVersion: v1
kind: ConfigMap
metadata:
  name: indefinite-studies-profiles-service-postgres-config
data:
  create-multiple-postgresql-databases.sh: |
{{ .Files.Get "create-multiple-postgresql-databases.sh" | indent 4 }}