apiVersion: apps/v1
kind: Deployment
metadata:
  name: kib-auto
  labels:
    name: kib-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kib-auto
  template:
    metadata:
      labels:
         name: kib-auto
    spec:
      containers:
        - name: kib-auto
          image: kibana:7.8.0               
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://{{ .Values.global.hostIp }}:{{ .Values.global.ports.external.elasticsearch }}"
          ports:
            - name: http
              containerPort: {{ .Values.global.ports.inner.kibana }}
---
apiVersion: v1
kind: Service
metadata:
  name: kib-auto
  labels:
    name: kib-auto
spec:
  selector:
    name: kib-auto
  type: NodePort
  ports:
    - nodePort: {{ .Values.global.ports.external.kibana }}
      port: {{ .Values.global.ports.inner.kibana }}
      protocol: TCP
      targetPort: {{ .Values.global.ports.inner.kibana }}