apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-kafka
  labels:
    app: indefinite-studies-kafka
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.global.ports.external.kafka }}
      port: {{ .Values.global.ports.inner.kafka }}
  selector:
    app: indefinite-studies-kafka