apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-feed-builder-service
  labels:
    app: indefinite-studies-feed-builder-service
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.global.ports.external.rest.feed }}
      name: rest
      port: {{ .Values.global.ports.inner.rest }}
    - nodePort: {{ .Values.global.ports.external.grpc.feed }}
      name: grpc
      port: {{ .Values.global.ports.inner.grpc }}
  selector:
    app: indefinite-studies-feed-builder-service