apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-feed-builder-service-redis
  labels:
    app: indefinite-studies-feed-builder-service-redis
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.global.ports.external.redis.feed }} 
      port: {{ .Values.global.ports.inner.redis }}
  selector:
    app: indefinite-studies-feed-builder-service-redis