apiVersion: apps/v1
kind: Deployment
metadata:
  name: indefinite-studies-feed-builder-service-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indefinite-studies-feed-builder-service-redis
  template:
    metadata:
      labels:
        app: indefinite-studies-feed-builder-service-redis
    spec:
      containers:
        - name: indefinite-studies-feed-builder-service-redis
          image: redis:6.2-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.global.ports.redis }}
          volumeMounts:
            - mountPath: /var/lib/redisdb/data
              name: indefinite-studies-feed-builder-service-redisdb
      volumes:
        - name: indefinite-studies-feed-builder-service-redisdb
          persistentVolumeClaim:
            claimName: indefinite-studies-feed-builder-service-redis-pv-claim