apiVersion: apps/v1
kind: Deployment
metadata:
  name: indefinite-studies-posts-service-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indefinite-studies-posts-service-postgres
  template:
    metadata:
      labels:
        app: indefinite-studies-posts-service-postgres
    spec:
      containers:
        - name: indefinite-studies-posts-service-postgres
          image: postgres:14.5
          lifecycle:
            postStart:
              exec:
                command: [ "sh", "-c", "/tmp/create-multiple-postgresql-databases.sh" ]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.global.ports.inner.postgres }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dev-secrets
                  key: POSTGRES_USER_POSTS
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-secrets
                  key: POSTGRES_PASSWORD_POSTS
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: dev-secrets
                  key: POSTGRES_DB_POSTS
                  optional: false
            - name: POSTGRES_MULTIPLE_DATABASES
              valueFrom:
                secretKeyRef:
                  name: dev-secrets
                  key: POSTGRES_MULTIPLE_DB_POSTS
                  optional: false
          volumeMounts:
            - mountPath: /var/lib/postgresql/data_posts
              name: indefinite-studies-posts-service-postgredb
            - mountPath: /tmp/
              name: postgres-config-output     
      initContainers:
        - name: copy-config 
          image: postgres:14.5
          command: [ "sh", "-c", "cp /usr/local/create-multiple-postgresql-databases.sh /tmp/create-multiple-postgresql-databases.sh" ]
          volumeMounts:
          - mountPath: /tmp/
            name: postgres-config-output
          - mountPath: /usr/local/
            name: postgres-config-volume
      volumes:
        - name: indefinite-studies-posts-service-postgredb
          persistentVolumeClaim:
            claimName: indefinite-studies-posts-service-postgres-pv-claim
        - name: postgres-config-output
          emptyDir: {}
        - name: postgres-config-volume
          configMap:
            name: postgres-config
            defaultMode: 0777
            items:
              - key: create-multiple-postgresql-databases.sh
                path: create-multiple-postgresql-databases.sh