apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-web-ui
  labels:
    app: indefinite-studies-web-ui
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: indefinite-studies-web-ui