apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-manual
  labels:
    app: es-manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-manual
  template:
    metadata:
      labels:
        app: es-manual
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: discovery.type
              value: single-node