apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-21T08:54:45Z"
  labels:
    app: es-manual
  name: es-manual
  namespace: default
  resourceVersion: "16527"
  uid: 3c125190-cbdb-4f1d-a1fd-f778f2bfdbcc
spec:
  clusterIP: 10.106.144.107
  clusterIPs:
  - 10.106.144.107
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31936
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: es-manual
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
