apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2022-09-22T02:22:05Z"
  generation: 2
  labels:
    app: kib-manual
  name: kib-manual
  namespace: default
  resourceVersion: "17989"
  uid: 421c3fcd-b8d3-48b1-8b45-6f2c9223263a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kib-manual
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kib-manual
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_HOSTS
          value: http://192.168.49.2:31936
        image: kibana:7.8.0
        imagePullPolicy: IfNotPresent
        name: kibana
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-09-22T02:23:03Z"
    lastUpdateTime: "2022-09-22T02:23:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-09-22T02:22:05Z"
    lastUpdateTime: "2022-09-22T02:23:09Z"
    message: ReplicaSet "kib-manual-646bd6b64" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
