apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-profiles-service
  labels:
    app: indefinite-studies-profiles-service
spec:
  type: NodePort
  ports:
    - name: rest
      port: 3005
    - name: grpc
      port: 50051
  selector:
    app: indefinite-studies-profiles-service