apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-notifications-service
  labels:
    app: indefinite-studies-notifications-service
spec:
  type: NodePort
  ports:
    - name: rest
      port: {{ .Values.global.ports.rest }}
    - name: grpc
      port: {{ .Values.global.ports.grpc }}
  selector:
    app: indefinite-studies-notifications-service