apiVersion: v1
kind: Service
metadata:
  name: smtp-dev-server
  labels:
    app: smtp-dev-server
spec:
  type: NodePort
  ports:
    - port: {{ .Values.global.ports.smtp }}
  selector:
    app: smtp-dev-server