apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-kafka
  labels:
    app: indefinite-studies-kafka
spec:
  type: NodePort
  ports:
    - port: {{ .Values.global.ports.kafka }}
  selector:
    app: indefinite-studies-kafka