apiVersion: apps/v1
kind: Deployment
metadata:
  name: indefinite-studies-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indefinite-studies-kafka
  template:
    metadata:
      labels:
        app: indefinite-studies-kafka
    spec:
      containers:
        - name: indefinite-studies-kafka
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.global.ports.kafka }}
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "indefinite-studies-zookeeper:{{ .Values.global.ports.zookeeper }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://indefinite-studies-kafka:9092,PLAINTEXT_HOST://indefinite-studies-kafka:{{ .Values.global.ports.kafka }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"