apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-zookeeper
  labels:
    app: indefinite-studies-zookeeper
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.global.ports.external.zookeeper }}
      port: {{ .Values.global.ports.inner.zookeeper }}
  selector:
    app: indefinite-studies-zookeeper