apiVersion: v1
kind: Service
metadata:
  name: indefinite-studies-zookeeper
  labels:
    app: indefinite-studies-zookeeper
spec:
  type: NodePort
  ports:
    - port: {{ .Values.global.ports.zookeeper }}
  selector:
    app: indefinite-studies-zookeeper