apiVersion: apps/v1
kind: Deployment
metadata:
  name: indefinite-studies-notifications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indefinite-studies-notifications-service
  template:
    metadata:
      labels:
        app: indefinite-studies-notifications-service
    spec:
      containers:
        - name: indefinite-studies-notifications-service
          image: indefinite-studies-notifications-service:{{ .Values.global.version.notifications }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.global.ports.inner.rest }}
              name: rest-port
            - containerPort: {{ .Values.global.ports.inner.grpc }}
              name: grpc-port     
          volumeMounts:
            - name: log-output
              mountPath: /tmp/
        - name: notifications-beat-auto
          image: elastic/filebeat:7.8.0
          env:
            - name: LOGSTASH_HOSTS
              value: "{{ .Values.global.hostIp }}:{{ .Values.global.ports.external.logstash }}"
          args: [
            "-c", "/etc/filebeat/filebeat.yml",
            "-e"
          ]
          volumeMounts:
          - name: log-output
            mountPath: /tmp/
          - name: notifications-beat-config
            mountPath: /etc/filebeat/
      volumes:
        - name: log-output
          emptyDir: {}
        - name: notifications-beat-config
          configMap:
            name: notifications-beat-config
            items:
              - key: filebeat.yml
                path: filebeat.yml