apiVersion: v1
kind: Service
metadata:
  name: smtp-dev-server
  labels:
    app: smtp-dev-server
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.global.ports.external.smtp }}
      port: {{ .Values.global.ports.inner.smtp }}
  selector:
    app: smtp-dev-server